"""add api_token to users

Revision ID: 7996397e071e
Revises: 7cbd38f192e1
Create Date: 2026-06-20 09:59:59.993534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7996397e071e'
down_revision = '7cbd38f192e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_api_token'), ['api_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_api_token'))
        batch_op.drop_column('api_token')

    # ### end Alembic commands ###
